Fixed ipv6 cidr on Regex
openshift/must-gather-clean pull request #85
Opened 2022-09-15 17:01 UTC by ansvu

2022-09-16 11:21 UTC, sairameshv commented
/ok-to-test

2022-09-16 11:34 UTC, sairameshv requested changes

2022-09-16 11:34 UTC, sairameshv commented on pkg/obfuscator/ip.go
> +	ipv6re        = `(([a-f0-9]{0,4}[:]){1,8}([0-9a-fA-F]{1,4}|::)+)`
Could you fix the linting issue?

2022-09-19 07:55 UTC, sairameshv commented
Please squash the change into a single commit.

2022-09-30 17:35 UTC, ansvu commented
squash into one commit is done. Please check. Thanks.

2022-10-02 07:08 UTC, sairameshv approved these changes

2022-10-02 07:08 UTC, sairameshv commented
LGTM

2022-10-02 07:11 UTC, merged